# Customization for Lancaster University's HEC cluster
# Use the HPC_CARPENTRY_CUSTOMIZATION variable to invoke these:
#
# > HPC_CARPENTRY_CUSTOMIZATION=episodes/files/customization/LAN_HEC_slurm/_config_options.yml
# > export HPC_CARPENTRY_CUSTOMIZATION
---
snippets: episodes/files/customization/LAN_HEC_slurm/snippets

local:
  prompt: "[you@laptop:~]$"
  shebang: "#!/usr/bin/env bash"

remote:
  name: "HEC"
  host_id: "FIXME_HEC"
  login: "wayland-2022.hec.lancs.ac.uk"
  host: "wayland-2022.hec.lancs.ac.uk"
  node: "comp04-13"
  location: "wayland-2022.hec.lancs.ac.uk"
  user: "user"
  prompt: 'user@wayland-2022:~$'
  shebang: "#!/bin/bash"

  fs:
    home: "/home/hpc/42"

  module_python3:
    python: "miniforge/20251003"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--partition=serial"
  queue:
    debug: "N/A"
    testing: "serial"
  reservation: "shortqos"
  qos: "short"
  account: "FIXME_HEC_account"
  project: "FIXME_HEC_training"
